services:
  - type: web
    name: civic-complaints-backend
    runtime: node
    plan: free
    region: oregon
    branch: milestone2-backup
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: NODE_VERSION
        value: 20.11.0
